#!/usr/bin/expect
#rpmmake - fast way to create rpm package inside the git repo without being root - http://safrm.net/projects/rpmmake
#author: Miroslav Safr <miroslav.safr@gmail.com>
# if you want to use non-empty pasphrase pass it by environmentall variable PASSPHRASE
#
spawn  {*}$argv
if { [ array names env PASSPHRASE ] != "" } {
        puts "\nPASSPHRASE exists and its value is $env(PASSPHRASE)\n"
        set pp $env($PASSPHRASE)
} else {
          set pp ""
}
expect -exact "Enter pass phrase: "
log_user 0
send -- "$pp\r"
expect eof
