#!/bin/sh
#rpmmake-changelog - generates rpm changelog from git log - https://github.com/safrm/rpmmake
VERSION=NA                                                                   
VERSION_DATE=NA

usage() {
    echo "usage: `basename $0` [-b <basename>] [-t <no_last_tags] [-a <my-message>]" 
    echo "fast script to create rpm changelog from git log - https://github.com/safrm/rpmmake"
    echo ""
    echo "args:"
    echo "  -b | --basename                   project name is taken from argument <my-project> instead of directory name"
    echo "  -t | --tags                       amount of last tags to generate changelog from"
    echo "  -a | --append-line <my-message>   appended last line (more info on http..)"
    echo "  -h | --help                       prints this help"
    echo ""
    echo "rpmmake: ${VERSION} ${VERSION_DATE}"
}
                                                                  
TAGS_COUNT=5 #default to limit size
APPEND_LINE=""
while [ $# -gt 0 ]; do
  case "$1" in
    -b|--basename) shift
               CUSTOM_BASENAME=$1    #clone directory has different name than project
               ;;
    -t|--tags) shift
               TAGS_COUNT=$1   
               ;;
    -a | --append-line) shift
	                APPEND_LINE=$1
                        ;;
    --version)    echo "`basename $0` $VERSION"
                  exit 0
                  ;;  
	* )       PWD_DIR=$PWD; cd $1   #from different directory
		  ;; 
  esac
  shift
done

#basename from 
BASENAME=`basename "$PWD"`
[ "x$CUSTOM_BASENAME" != "x" ] && BASENAME=$CUSTOM_BASENAME


#generate
echo "%changelog"  > $BASENAME.changes

#+1 number correction because we need previous tag info
TAGS_COUNT=$(($TAGS_COUNT+1))
TAGS=`git tag | tail -$TAGS_COUNT | sort -u -r`
if [ "x$TAGS" = "x" ]; then
   echo "You need at least one tag. Exiting.."
   exit 1
fi

#tags & commits
FIRST_TAG=
#previous is in this case newer
HIGHER_TAG=
HIGHER_TAG_HASH=
for TAG in $TAGS
do
  #not tagged changes
  TAG_HASH=`git rev-list $TAG | head -n 1` 
  if [ "x$FIRST_TAG" = "x" ]; then
        FIRST_TAG=$TAG
	echo "first tag: $FIRST_TAG - $TAG_HASH" 
        HEAD_VERSION_COMMITS=`git log $TAG_HASH..HEAD --pretty=format:'- %s' 2> /dev/null`
        HEAD_VERSION_TAG=`git describe --tags  --dirty=* 2> /dev/null`
        LAST_COMMIT_DATE=`git log -1 --pretty=format:'%ad' | awk '{print $1,$2,$3,$5}'`
        LAST_COMMIT_AUTHOR=`git log -1 --pretty=format:'%an <%ae>'`
	if [ "x$HEAD_VERSION_COMMITS" != "x" ]; then
		echo "* $LAST_COMMIT_DATE $LAST_COMMIT_AUTHOR - $HEAD_VERSION_TAG"  >> $BASENAME.changes
                git log $TAG_HASH..HEAD --pretty=format:'- %s' 2> /dev/null >> $BASENAME.changes
		echo "\n"  >> $BASENAME.changes 
        fi
  fi
  if [ "x$HIGHER_TAG_HASH" != "x" ]; then
	#tag changes for each tag
	TAG_COMMIT_DATE=`git log $HIGHER_TAG_HASH -1 --pretty=format:'%ad' | awk '{print $1,$2,$3,$5}'` 
	TAG_COMMIT_AUTHOR=`git log $HIGHER_TAG_HASH -1 --pretty=format:'%an <%ae>'`
	echo "* $TAG_COMMIT_DATE $LAST_COMMIT_AUTHOR - $HIGHER_TAG"  >> $BASENAME.changes 
	git log $TAG_HASH..$HIGHER_TAG_HASH --pretty=format:'- %s'  >> $BASENAME.changes 
	echo "\n"  >> $BASENAME.changes 
  fi
  HIGHER_TAG=$TAG
  HIGHER_TAG_HASH=$TAG_HASH
done

#extra line
echo $APPEND_LINE  >> $BASENAME.changes 
echo "changelog for $TAGS_COUNT tags updated in ./$BASENAME.changes"


