#!/bin/sh
#rpmmake-changelog - generates rpm changelog from git log - http://safrm.net/projects/rpmmake
#author: Miroslav Safr <miroslav.safr@gmail.com>
VERSION=NA
VERSION_DATE=NA

usage() {
    echo "usage: `basename $0` [-b <basename>] [-t <no_last_tags] [-a <my-message>]" 
    echo "fast script to create rpm changelog from git log - http://safrm.net/projects/rpmmake"
    echo ""
    echo "args:"
    echo "  -b  | --basename                   project name is taken from argument <my-project> instead of directory name"
    echo "  -t  | --tags                       amount of last tags to generate changelog from"
    echo "  -sv | --set-version <version>      sets latest changelog version"
    echo "  -a  | --append-line <my-message>   appended last line (more info on http..)"
    echo "  -h  | --help                       prints this help"
    echo ""
    echo "rpmmake: ${VERSION} ${VERSION_DATE}"
}

TAGS_COUNT=6 #default to limit size
APPEND_LINE=""
while [ $# -gt 0 ]; do
  case "$1" in
    -b|--basename) shift
               BASENAME=$1    #clone directory has different name than project
               ;;
    -t|--tags) shift
               TAGS_COUNT=$1   
               ;;
    -a | --append-line) shift
	                APPEND_LINE=$1
                        ;;
    -sv|--set-version) shift
               RPM_VERSION=$1           #custom version
			   ;;
    -V | --version)    echo "`basename $0`  ${VERSION} ${VERSION_DATE}"
                  exit 0
                  ;;  
	* )       PWD_DIR=$PWD; cd $1   #from different directory
		  ;; 
  esac
  shift
done

#basename from arg or directory
[ -z "$BASENAME" ] && BASENAME=`basename "$PWD"`
CHANGES_FILE=$BASENAME.changes

#generate
echo "%changelog"  > $CHANGES_FILE

#+1 number correction because we need previous tag info
TAGS_COUNT=$(($TAGS_COUNT+1))
TAGS=`git tag | sort -V -u -r | head -$TAGS_COUNT`

#tags & commits
FIRST_TAG=
#previous is in this case newer
HIGHER_TAG=
HIGHER_TAG_HASH=
for TAG in $TAGS
do
  #not tagged changes
  TAG_HASH=`git rev-list $TAG | head -n 1` 
  if [ -z "$FIRST_TAG" ]; then
        FIRST_TAG=$TAG
		echo "first tag: $FIRST_TAG - $TAG_HASH" 
        HEAD_VERSION_COMMITS=`git log $TAG_HASH..HEAD --pretty=format:'- %s' 2> /dev/null`
        HEAD_VERSION_TAG=`git describe --tags  --dirty=* 2> /dev/null`
        LAST_COMMIT_DATE=`git log -1 --pretty=format:'%ad' | awk '{print $1,$2,$3,$5}'`
        LAST_COMMIT_AUTHOR=`git log -1 --pretty=format:'%an <%ae>'`
		if [ ! -z "$HEAD_VERSION_COMMITS" ]; then
			if [ -z "$RPM_VERSION" ]; then
				#we use last tag + git hash
				echo "* $LAST_COMMIT_DATE $LAST_COMMIT_AUTHOR - $HEAD_VERSION_TAG"  >> $CHANGES_FILE
		        git log $TAG_HASH..HEAD --pretty=format:'- %s' 2> /dev/null >> $CHANGES_FILE
				echo "\n"  >> $CHANGES_FILE
			else
				#we use given version
				echo "* $LAST_COMMIT_DATE $LAST_COMMIT_AUTHOR - $RPM_VERSION"  >> $CHANGES_FILE
		        git log $TAG_HASH..HEAD --pretty=format:'- %s' 2> /dev/null >> $CHANGES_FILE
			fi
        fi
  fi
  if [ ! -z "$HIGHER_TAG_HASH" ]; then
	#tag changes for each tag
	TAG_COMMIT_DATE=`git log $HIGHER_TAG_HASH -1 --pretty=format:'%ad' | awk '{print $1,$2,$3,$5}'` 
	TAG_COMMIT_AUTHOR=`git log $HIGHER_TAG_HASH -1 --pretty=format:'%an <%ae>'`
	if [ ! -z "$HEAD_VERSION_COMMITS" -a "x$HIGHER_TAG" = "x$DEB_VERSION" ]; then
		:
	else
		#we don't repeat highest version 2x
		echo "* $TAG_COMMIT_DATE $TAG_COMMIT_AUTHOR - $HIGHER_TAG"  >> $CHANGES_FILE 
	fi
	git log $TAG_HASH..$HIGHER_TAG_HASH --pretty=format:'- %s'  >> $CHANGES_FILE 
	echo "\n"  >> $CHANGES_FILE 
  fi
  HIGHER_TAG=$TAG
  HIGHER_TAG_HASH=$TAG_HASH
done

#before first tag
if [ `echo "$TAGS" | wc -l` -lt $TAGS_COUNT ]; then
	BEFORE_FIRST_TAG_COMMITS=`git log $TAG_HASH --pretty=format:'- %s' 2> /dev/null`
	if [ ! -z "$BEFORE_FIRST_TAG_COMMITS" ]; then
		TAG_COMMIT_DATE=`git log $TAG_HASH -1 --pretty=format:'%ad' | awk '{print $1,$2,$3,$5}'` 
		TAG_COMMIT_AUTHOR=`git log $TAG_HASH -1 --pretty=format:'%an <%ae>'`
		#when there are no tags
		if [ -z "$TAGS" ]; then
		   	echo "There are no tags."
			LAST_COMMIT_DATE=`git log -1 --pretty=format:'%ad' | awk '{print $1,$2,$3,$5}'`
			LAST_COMMIT_AUTHOR=`git log -1 --pretty=format:'%an <%ae>'`
			if [ -z "$RPM_VERSION" ]; then
				RPM_VERSION=0.0.0
			fi
			echo "* `date +"%a %b %d %Y"` `git config user.name` <`git config user.email`>  - $RPM_VERSION"  >> $CHANGES_FILE
		else 
			echo "* $TAG_COMMIT_DATE $TAG_COMMIT_AUTHOR - $TAG"  >> $CHANGES_FILE 
		fi
		git log $TAG_HASH --pretty=format:'- %s'  >> $CHANGES_FILE 
		echo "\n"  >> $CHANGES_FILE 
	fi
fi 
#extra line
if [ ! -z "$APPEND_LINE" ]; then
	echo $APPEND_LINE  >> $CHANGES_FILE
fi
echo "rpm changelog for $TAGS_COUNT tags updated in ./$CHANGES_FILE"


