'\" t
.\"     Title: rpmmake-expect
.\"    Author: Miroslav Safr <miroslav.safr@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 20150310_1133
.\"    Manual: More than fast script to create rpm package inside the git repo without being root
.\"    Source: rpmmake 1.1.9
.\"  Language: English
.\"
.TH "RPMMAKE\-EXPECT" "1" "20150310_1133" "rpmmake 1.1.9" "More than fast script to creat"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rpmmake-expect \- Rpm signing wrapper for expect
.SH "SYNOPSIS"
.HP \w'\fBrpmmake\-expect\ [ARGS]\fR\ 'u
\fBrpmmake\-expect [ARGS]\fR
.SH "DESCRIPTION"
.PP
Fast script to create rpm package inside the git repo without being root\&. Rpm signing (or other command) wrapper for expect which answers passphrase question\&. By default uses empty passphrase or exported veriable <PASSPHRASE>\&.
.SH "ARGS"
.PP
Wrapped commnad with arguments\&.
.SH "SEE ALSO"
.PP
rpmmake(1), rpmmake\-changelog(1), rpmmake\-debchangelog(1)\&.
\m[blue]\fB\%http://safrm.net/projects/rpmmake/\fR\m[]
.SH "AUTHOR"
.PP
Miroslav Šafr <miroslav\&.safr@gmail\&.com>
.SH "LICENSE"
.PP
LGPL2
.SH "AUTHOR"
.PP
\fBMiroslav Safr\fR <\&miroslav\&.safr@gmail\&.com\&>
.RS 4
Author and maintainer
.RE
